#
# Upgrade a neo-node with the new neo-cli defined in group_vars
# The new neo-cli must be compatible with the old chain format, else needs manual upgrade.
#
---
- hosts:
  - node_neo
  gather_facts: false
  become: yes

  tasks:
  - name: Stop neonode service
    systemd:
      name: neonode
      state: stopped

  - name: Delete previous neo-cli backup directory
    command: "rm -rf {{ neonode_root_directory }}/neo-cli.bak"

  - name: Move neo-cli directory to neo-cli.bak
    command: "mv {{ neonode_root_directory }}/neo-cli {{ neonode_root_directory }}/neo-cli.bak"

  - name: Download neo-cli and verify checksum
    get_url:
      url: "{{ neo_cli_download }}"
      dest: "/tmp/neo-cli.zip"
      mode: 0440
      checksum: "sha256:{{ neo_cli_checksum }}"
      owner: "{{ project_user }}"
      group: "{{ project_group }}"

  - name: Extract neo-cli.zip
    unarchive:
      src: "/tmp/neo-cli.zip"
      dest: "{{ neonode_root_directory }}/"
      remote_src: yes
      owner: "{{ project_user }}"
      group: "{{ project_group }}"

  - name: "Copy {{ neo_cli_config_file }} to protocol.json"
    copy:
      src: "{{ neonode_root_directory }}/neo-cli/{{ neo_cli_config_file }}"
      dest: "{{ neonode_root_directory }}/neo-cli/protocol.json"
      remote_src: yes
      owner: "{{ project_user }}"
      group: "{{ project_group }}"

  - name: Move Chain directory into new neo-cli directory
    command: "mv {{ neonode_root_directory }}/neo-cli.bak/{{ neo_cli_chain_dir }} {{ neonode_root_directory }}/neo-cli/{{ neo_cli_chain_dir }}"

  - name: Start neonode service
    systemd:
      name: neonode
      state: started

